# _config.yml

# Site settings
title: "My Resume"
baseurl: ""  # Set this if hosting under a subdirectory
url: "https://yourgithubusername.github.io"

author:
  name: "Your Name"
  email: "your.email@example.com"
  github: "yourgithubusername"
  linkedin: "your-linkedin-url"
  portfolio: "your-portfolio-url"

theme: jekyll-theme-minimal